CREATE TABLE IF NOT EXISTS WEATHER_CALENDER (
  CALENDERDATE  DATE PRIMARY KEY,
  WEATHER_TYPE_CD  varchar(10) NOT NULL,
  CONSTRAINT FK_WEATHER_TYPE_CD FOREIGN KEY (WEATHER_TYPE_CD) REFERENCES WEATHER_TYPE(WEATHER_TYPE_CD)
);